name: Update Version

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "*/60 * * * *" # every 30 minutes

permissions:
  contents: write  # allow push access

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch remote JSON
        run: |
          set -e
          RESPONSE=$(curl -s --fail "https://play.rajkumaar.co.in/json?id=com.iandreop.weatherv2" || echo "")
          if [ -z "$RESPONSE" ]; then
            echo "Failed to fetch data"
            echo "updated=false" >> $GITHUB_ENV
            exit 0
          fi
          VERSION=$(echo "$RESPONSE" | jq -r '.version' || echo "")
          if [ -z "$VERSION" ] || [ "$VERSION" == "null" ]; then
            echo "Invalid version received"
            echo "updated=false" >> $GITHUB_ENV
            exit 0
          fi
          echo "$VERSION" > new_version.txt

      - name: Compare versions and update if newer
        if: env.updated != 'false'
        run: |
          NEW_VERSION=$(cat new_version.txt)
          CURRENT_VERSION=$(cat ./version.json)

          echo "Current: $CURRENT_VERSION"
          echo "New: $NEW_VERSION"

          version_gt() {
            [ "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1" ]
          }

          if version_gt "$NEW_VERSION" "$CURRENT_VERSION"; then
            echo "$NEW_VERSION" > ./version.json
            echo "updated=true" >> $GITHUB_ENV
          else
            echo "No update needed"
            echo "updated=false" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Authenticate using GITHUB_TOKEN
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add ./version.json
          git commit -m "chore: bump version to $(cat new_version.txt)"
          git push origin HEAD:${{ github.ref }}